[telegram]
bot_token = "7607027514:AAH92OWm-yVLjeEi2-e2k-4iA4-9gdXSwkQ"
chat_id   = "8074434283"

[twelvedata]
api_key = "91bd02e2b9774a1591bdde0b6e382e96"

[alphavantage]
alva_api_key = "F4L15PTO0OVERK65"